
# This is the main configuration file for Supabase CLI.
# It is stored in the project root directory (.supabase).
project_id = "ahodvrugfywgcpreeocn"

[api]
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[functions.create-notification]
verify_jwt = false

[functions.generate-invoice-notifications]
verify_jwt = false
