
# This is the config file for your Supabase project.
# It is used to allow running Edge Functions locally.
# Learn more: https://supabase.com/docs/guides/functions/local-development

project_id = "svrsfzpkqleyzfllmkcd"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:5173"]
jwt_expiry = 3600
enable_signup = true

[functions.create-invoice]
verify_jwt = true

[functions.create-payment-link]
verify_jwt = true

[functions.get-invoice]
verify_jwt = true

[functions.list-invoices]
verify_jwt = true

[functions.send-invoice]
verify_jwt = true

[functions.initiate-stripe-connect]
verify_jwt = true

[functions.stripe-connect-callback]
verify_jwt = true

[functions.check-stripe-connection]
verify_jwt = true

[functions.disconnect-stripe-account]
verify_jwt = true
