
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swxmaclvcgyydjqdduey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3eG1hY2x2Y2d5eWRqcWRkdWV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTM4NzksImV4cCI6MjA2MzI4OTg3OX0.wmZRghGzyoFOSFOlljseHS8orQQjb3xYxForItun2uU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
